### ISSUE TITLE
oplog.stop() crashing server

### ISSUE THREAD

**Issue by bjoshuanoah** [cayasso/mongo-oplog#2]
I'm calling oplog.stop() and it's crashing the server.

Here is the stack trace:

    /Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;      
              ^
    MongoError: Connection Closed By Application
    at Object.toError (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at ReplSet.close (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/node_modules/mongodb/lib/mongodb/connection/repl_set/repl_set.js:250:36)
    at Db.close (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/node_modules/mongodb/lib/mongodb/db.js:347:21)
    at Connection.close (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/lib/connect.js:97:11)
    at Oplog.stop (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/mongo-oplog/lib/index.js:214:13)
    at Object.Watch.stop (/Users/bnoah/Dev/socialcasino/dbHistory/server/modules/dbWatch/services/watch/index.js:43:33)
    at exports.end (/Users/bnoah/Dev/socialcasino/dbHistory/server/modules/dbWatch/controllers/watch.js:41:8)
    at Layer.handle [as handle_request] (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/bnoah/Dev/socialcasino/dbHistory/server/node_modules/express/lib/router/route.js:100:13)
    at /Users/bnoah/Dev/socialcasino/dbHistory/server/modules/common/middleware/auth.js:12:5

I also tried adding the oplog.stop() functionality to the mocha test and it failed there as well. It didn't even connect and timed out.

**Comment by cbratschi** [comment]
I have the exactly same problem. However, in my case I want to shutdown the oplog connection once it is no longer being used.

I tried to catch the exception but the complete app was still crashing, even if domains were used.

The error handler was never called:

            this.oplog.conn.db.on('error', function (err) {
                console.error(err.message); //FIXME
            });

@cayasso any plans to support a more efficient filtering? Currently all oplog changes are transferred from MongoDB which is quite some overhead for Big Data and realtime use cases.

**Comment by yskeat** [comment]
Same problem here.
My use case is using the oplog to notify app admin for data change. 
Once admin logout, I will stop the oplog without exit my backend engine.
But call oplog.stop() will cause my backend engine crash.

**Comment by cayasso** [comment]
@yskeat can you please try the develop branch with has 0.2.x https://github.com/cayasso/mongo-oplog/tree/develop this will be the next release, the api is a bit different but should work fine, you can check the tests for api usage

**Comment by yskeat** [comment]
Sorry to tell I decided to switch to RDBMS due to mongodb query limitation.

**Comment by cayasso** [comment]
Ok, I am closing this.
