### ISSUE TITLE
cursor error

### ISSUE THREAD

**Issue by ORESoftware** [cayasso/mongo-oplog#22]
On occasion I get this error, which currently crashes the server that reads the MongoDB oplog:

```
error event: { [MongoError: cursor killed or timed out] name: 'MongoError', message: 'cursor killed or timed out' }

/Users/amills001c/WebstormProjects/ORESoftware/mongodb-oplog-listener/node_modules/mongo-oplog/node_modules/mongodb/lib/utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
MongoError: cursor killed or timed out
    at queryCallback (/Users/amills001c/WebstormProjects/ORESoftware/mongodb-oplog-listener/node_modules/mongo-oplog/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:87:23)
    at Callbacks.emit (/Users/amills001c/WebstormProjects/ORESoftware/mongodb-oplog-listener/node_modules/mongo-oplog/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/amills001c/WebstormProjects/ORESoftware/mongodb-oplog-listener/node_modules/mongo-oplog/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:23)
    at Socket.<anonymous> (/Users/amills001c/WebstormProjects/ORESoftware/mongodb-oplog-listener/node_modules/mongo-oplog/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

```

is this a known problem?

**Comment by jdarling** [comment]
Line 226 in index.js needs to be updated, currently it is:

```
} else if (/cursor timed out/.test(err.message)) {
```

For new Mongo errors it should be:

```
} else if (/cursor (killed or )?timed out/.test(err.message)) {
```

**Comment by cayasso** [comment]
@ORESoftware @jdarling mongo-oplog@1.0.0 is out with latest fixes. Thanks for reporting issues and for being patient :)
